name: build
on: [push]
jobs:
  build-workspace:
    runs-on: [self-hosted, container-build]
    container:
      image: ubuntu:22.04
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Prepare System
        run: |
          apt update
          apt install -y python3-pip
          apt install -y openssh-client git pkg-config python3 python3-setuptools python3-wheel cmake build-essential googletest python3-dev pybind11-dev libpython3-dev libopencv-dev libeigen3-dev
      - uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: |
          python3 -m pip install -r requirements.txt
          python3 setup.py bdist_wheel

      - name: Test
        shell: bash
        run: |
          python3 setup.py test
